alias simpleServer="python -m SimpleHTTPServer"
alias gitX="gitX --all &"
alias chromeCrossD="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security"
alias gr="grunt"
alias gap="git add -p"
alias hisgrep="history | grep -i"
alias gspresp="git stash && git pull --rebase && git stash pop"
alias ls="ls -GF"
alias grep="grep --color=auto -inH"
alias ll="ls -al"
